### ISSUE TITLE
Este páramo

### ISSUE THREAD

**Issue by ez2torta** [FelipeLema/display-lag-scraping#1]
Este monitor está en winpy, el manolo se lo compró la semana pasada y es entero de weno

https://www.amazon.com/dp/B01CX26WIG/?tag=dislag-20

(no es exactamente el mismo pero es parecido el modelo.. qué hacer?)
https://www.winpy.cl/venta/monitor-samsung-curvo-23-5-lc24f390fh/

Está pelúo tratar de deducir cuestiones, esop

**Comment by FelipeLema** [comment]
¿Winpy no está en solotodo? ¿qué otros sitios no están en solotodo? los agrego para búsqueda localizada con duckduckgo o google

**Comment by ez2torta** [comment]
Me parece que si está.. he visto algunas motherboards y relacionados que linkean a winpy..

el problema es que no todos los monitores sin lac están en displaylac 

http://www.solotodo.com/products/25606-samsung-lc24f390fhlxzs/
